//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreComputer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDatHang
    {
        public int maHD { get; set; }
        public int maHang { get; set; }
        public int soLuong { get; set; }
        public Nullable<System.DateTime> ngayDatHang { get; set; }
        public double thanhTien { get; set; }
    
        public virtual DatHang DatHang { get; set; }
        public virtual HangHoa HangHoa { get; set; }
    }
}
