//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreComputer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangHoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HangHoa()
        {
            this.ChiTietDatHang = new HashSet<ChiTietDatHang>();
        }
    
        public int maHang { get; set; }
        public int maLoai { get; set; }
        public int maNCC { get; set; }
        public string tenHang { get; set; }
        public System.DateTime ngayNhap { get; set; }
        public double giaMoi { get; set; }
        public double giaCu { get; set; }
        public int soLuong { get; set; }
        public string hinhAnh { get; set; }
        public string moTa { get; set; }
        public string maTaChiTiet { get; set; }
        public string giamGia { get; set; }
        public string trangThaiSP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDatHang> ChiTietDatHang { get; set; }
        public virtual LoaiHang LoaiHang { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
