//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreComputer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TuVanKH
    {
        public int maTV { get; set; }
        public Nullable<int> maKH { get; set; }
        public string tenKH { get; set; }
        public string soDienThoai { get; set; }
        public string email { get; set; }
        public string kieuTuVan { get; set; }
        public string loiNhan { get; set; }
        public string tinhTrang { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
